
/**
 * Utilities for writing Dart files to disk, including import management and directory creation.
 *
 * @module dartWriter
 */

import * as path from 'path';
import { ensureDirExists, writeFile } from './fileUtils.js';


/**
 * Writes a Dart file to disk, ensuring the directory exists and prepending imports.
 *
 * @param filePath - The absolute path to the Dart file to write.
 * @param code - The Dart code to write to the file.
 * @param imports - A set of import paths to include at the top of the file.
 */
export function writeDartFile(filePath: string, code: string, imports: Set<string>): void {
    const dartDir = path.dirname(filePath);
    ensureDirExists(dartDir);
    const finalCode = `// Generated by dartify\n\nimport 'dart:js_interop';\n${Array.from(imports).map(imp => `import '${imp}';\n`).join('')}\n${code}`;
    writeFile(filePath, finalCode);
}
